### PR TITLE
added short_name to administrative_area

### PR DESCRIPTION
**Pull request by bziegler**
Hi,

nice work. I like the module. 
For my project, I would need to retrieve also the short_name of the administrative area. I added that functionality (+test) in this pull request. Let me know if you can consider it.

Thanks

### CODE REVIEW

**Comment by slawek87** [comment]
nice work! I merged your request :)

**Comment by slawek87** [comment]
btw. can you update README.md and add there info about short_name? :)

**Comment by bziegler** [comment]
ok great! 
I updated the two files in the same branch. The attributes of the administrative_area are only mentioned in the code example in the README. I guess that should be explanatory enough. You want me to create another pull request?

**Comment by slawek87** [comment]
yes.. make pull request :)

**Pull request merged**
